"""
Writes the transcript, the subtitle file and the timeline from the recorded
narration.

narration.wav is the authority. narration_text.py holds what is said and when,
and build_video.py holds which picture is on screen from which second. This
script only turns those two tables into readable documents, so they cannot drift
from the video.

Usage:
    python submission/video/build_narration.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_video import SHOTS, write_srt  # noqa: E402
from narration_text import CUES, NARRATION_SECONDS, VIDEO_SECONDS  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPT_MD = os.path.join(HERE, "FINAL_VIDEO_SCRIPT.md")
SRT = os.path.join(HERE, "FINAL_VIDEO_SUBTITLES.srt")
TIMELINE_MD = os.path.join(HERE, "FINAL_VIDEO_TIMELINE.md")


def clock(seconds: float) -> str:
    return "%d:%04.1f" % (int(seconds // 60), seconds % 60)


def scene_label(kind: str, payload: dict) -> str:
    if kind in ("shot", "appshot"):
        return "%s, %s" % (payload["id"], payload["caption"])
    return payload.get("title", payload.get("quote", "")).replace("\n", " ")


def scenes():
    rows = []
    for index, (start, kind, payload) in enumerate(SHOTS):
        end = SHOTS[index + 1][0] if index + 1 < len(SHOTS) else VIDEO_SECONDS
        said = [c[2] for c in CUES if start <= c[0] < end]
        rows.append((index + 1, start, end, kind, scene_label(kind, payload), said))
    return rows


def write_script(rows) -> None:
    words = sum(len(c[2].split()) for c in CUES)
    lines = [
        "# GridResolve AI: final video narration, as recorded",
        "",
        "Generated by `build_narration.py` from `narration_text.py`.",
        "",
        "This is a transcript of `narration.wav`, not a script to be read. I recorded the",
        "narration on 2026-09-21. The recording is %.3f seconds long and is used at its own" % NARRATION_SECONDS,
        "speed, unedited. The words and their times come from a local, offline",
        "transcription of that file, corrected where it misheard a project term. The video",
        "is %.1f seconds, which leaves a short closing frame after the last word." % VIDEO_SECONDS,
        "",
        "%d words, %d subtitle cues, %d scenes." % (words, len(CUES), len(rows)),
        "",
        "One spoken phrase is looser than the record, and the picture corrects it: I say",
        "\"nine GPT-5 agents\". The deployment is gpt-5-mini, which the slide and the Foundry",
        "capture both show.",
        "",
    ]
    for number, start, end, _, label, said in rows:
        lines += ["## Scene %d, %s to %s" % (number, clock(start), clock(end)), "", "On screen: %s" % label, ""]
        lines += ["> %s" % " ".join(said), ""] if said else ["No new sentence starts in this scene.", ""]
    with open(SCRIPT_MD, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))


def write_timeline(rows) -> None:
    lines = [
        "# GridResolve AI: final video timeline",
        "",
        "Generated by `build_narration.py` from the SHOTS table in `build_video.py`.",
        "Scene starts were read off the word times of the recording, so each picture",
        "changes on the sentence it belongs to.",
        "",
        "| Scene | Start | End | Seconds | Kind | On screen |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for number, start, end, kind, label, _ in rows:
        lines.append("| %d | %s | %s | %.1f | %s | %s |" % (number, clock(start), clock(end), end - start, kind, label))
    lines += ["", "Total: %.1f seconds. Limit: strictly under 180." % VIDEO_SECONDS, ""]
    with open(TIMELINE_MD, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))


def main() -> int:
    rows = scenes()
    write_script(rows)
    write_timeline(rows)
    write_srt(None, SRT)
    print("scenes      : %d" % len(rows))
    print("cues        : %d" % len(CUES))
    print("total words : %d" % sum(len(c[2].split()) for c in CUES))
    print("video       : %.1f seconds" % VIDEO_SECONDS)
    return 0


if __name__ == "__main__":
    sys.exit(main())
